sequenceDiagram
    participant browser
    participant server
    
    browser->>server:POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa;
    activate server;
    server-->> browser:Responds  with a status code 201 that says object is created
     Note right of browser:This time the website doesnt reload, JS dynamically edit the website .
    



   
